openapi: "3.0.3"
info:
  title: "Subsistema 3: gestión de trabajos de un taller"
  version: "1.0.0"
  description: "Asignatura AOS: grupo 1"
  license:
    name: AOSGrupo1
    url: 'https://github.com/miguel-benito-martin/practica1_AOS'
  contact:
    name: Arquitecturas Orientadas a Servicios
    url: 'https://moodle.upm.es/titulaciones/oficiales/mod/assign/view.php?id=1320916'
    email: alberto.romartin@alumnos.upm.es
#servers:
#  - url: '{schema}://{server}:{port}/{basePath}'
#    description: Servidor local
#    variables:
#      schema:
#        description: Esquema
#        default: http
#       enum:
#         - http
#         - https
#     server:
#       description: Nombre del servidor
#       default: 127.0.0.1
#     port:
#       description: Número de puerto
#       default: '8080'
#     basePath:
#       description: Ruta base
#       default: api/v1
tags:
  - name: 'Trabajos'
    description: Trabajos de los usuarios
paths:
  /trabajo:
    get:
    post:
    options:
  /trabajo/{trabajoId}:


components:
  schemas:
  headers:
  parameters:
  responses:



